# Generated by Django 2.1.15 on 2023-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('account', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Car_in_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('begintime', models.DateTimeField()),
                ('carport', models.IntegerField(verbose_name='车位')),
            ],
            options={
                'db_table': 'car_in_record',
            },
        ),
        migrations.CreateModel(
            name='Car_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号')),
                ('carport', models.IntegerField(verbose_name='车位')),
                ('begintime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('genre', models.IntegerField(null=True, verbose_name='种类')),
            ],
            options={
                'db_table': 'car_manage',
            },
        ),
        migrations.CreateModel(
            name='Car_out_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('endtime', models.DateTimeField()),
                ('carport', models.IntegerField(verbose_name='车位')),
            ],
            options={
                'db_table': 'car_out_record',
            },
        ),
        migrations.CreateModel(
            name='Car_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('genre', models.IntegerField(verbose_name='种类')),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
            options={
                'db_table': 'car_record',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateTimeField(null=True)),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
        migrations.CreateModel(
            name='Extra_charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('is_valid', models.BooleanField(default=False)),
                ('vip_begintime', models.DateTimeField(null=True)),
                ('vip_deadline', models.DateTimeField(null=True)),
                ('money', models.IntegerField(verbose_name='收费')),
            ],
            options={
                'db_table': 'extra_charge',
            },
        ),
        migrations.CreateModel(
            name='License_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(blank=True, null=True, unique=True, upload_to='car_imgs')),
                ('car_num', models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号')),
                ('is_inside', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'license_plate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('carnum', models.CharField(max_length=32, unique=True, verbose_name='车牌号')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('level', models.IntegerField(verbose_name='会员套餐')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
