# Generated by Django 2.1.15 on 2024-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_manage_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号')),
                ('carport', models.IntegerField(verbose_name='车位')),
                ('begintime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('genre', models.IntegerField(null=True, verbose_name='种类')),
                ('parking', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'car_manage_test',
            },
        ),
    ]
