# Generated by Django 2.1.15 on 2024-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_manage_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_manage_test',
            name='pos',
            field=models.CharField(max_length=32, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='car_manage_test',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='是否存在车辆'),
        ),
    ]
